### ISSUE TITLE
How to set gas here?

### ISSUE THREAD

**Issue by Ruben1987Alex** [benreichman/AAVE-V2-FlashLoan-Uniswap-V2-Arbitrage#1]
// TODO: Include gas prices in profitable equation.
            const profitable = amt < ethers.utils.formatEther(getAmountsOut3[1].toString());
            console.log("Profitable?: ", profitable);
            if (profitable) {
                console.log('Profitable route discovered : ' + flashAsset[0].symbol +' -> '+ _token2.symbol + ' -> WETH -> ' + flashAsset[0].symbol )
                console.log('Swap 1 Received: ', ethers.utils.formatEther(getAmountsOut[1].toString()) + ' '+ _token2.symbol);
                console.log('Swap 2 Received: ', ethers.utils.formatEther(getAmountsOut2[1].toString()) + ' WETH');
                console.log('Swap 3 Received: ', ethers.utils.formatEther(getAmountsOut3[1].toString()) + ' ' + flashAsset[0].symbol);              
                await swapFunc("0x6B175474E89094C44Da98b954EedeAC495271d0F", _token2, WETH, amtToSwap,)

**Comment by benreichman** [comment]
Sorry for the late response! But to estimate gas there are a couple of methods, but this is one way of doing so :

First get the gas price : 
const gasPrice = await provider.getGasPrice();

Then... Estimate function gas used via .estimateGas : 
const swapFuncFee = await flashLoanContract.estimateGas.myFlashLoanCall("0x6B175474E89094C44Da98b954EedeAC495271d0F", _token2, WETH, amtToSwap);

Then...final gas estimate : 
const finalGasPrice = gasPrice * swapFuncFee;


**Note that these estimates aren't always exact and perfect.
